name: PyPI CI

on:
  push:
    paths:
      - "pypi/**"
      - ".github/workflows/pypi-ci.yml"
      - ".github/workflows/pypi-check.yml"
  pull_request:
    paths:
      - "pypi/**"
      - ".github/workflows/pypi-ci.yml"
      - ".github/workflows/pypi-check.yml"

jobs:
  check:
    uses: ./.github/workflows/pypi-check.yml
