name: Python CI

on:
  push:
    paths:
      - "python/**"
      - ".github/workflows/python-ci.yml"
      - ".github/workflows/python-check.yml"
  pull_request:
    paths:
      - "python/**"
      - ".github/workflows/python-ci.yml"
      - ".github/workflows/python-check.yml"

jobs:
  check:
    uses: ./.github/workflows/python-check.yml
